"""empty message

Revision ID: 0679232fcf8f
Revises: c0057970ec1b
Create Date: 2025-03-26 19:05:50.678916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0679232fcf8f'
down_revision = 'c0057970ec1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.drop_column('client')
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_projet_client', 'client', ['client_id'], ['id'])
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('adresse', sa.String(length=200), nullable=True),
    sa.Column('code_postal', sa.String(length=5), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('mail', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint('fk_projet_client', type_='foreignkey')
        batch_op.drop_column('client_id')
    op.drop_table('client')
    # ### end Alembic commands ###
