"""Add solde_initial and etat at CompteComptable

Revision ID: 1b932367ab71
Revises: d1310cb15294
Create Date: 2025-04-09 10:01:44.678893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b932367ab71'
down_revision = 'd1310cb15294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compte_comptable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solde_initial', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('etat', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compte_comptable', schema=None) as batch_op:
        batch_op.drop_column('etat')
        batch_op.drop_column('solde_initial')

    # ### end Alembic commands ###
