"""Ajout du modele RagDocument

Revision ID: 7e0157e7f2f0
Revises: c69d0b79bfd8
Create Date: 2025-05-06 19:42:10.507342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0157e7f2f0'
down_revision = 'c69d0b79bfd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['projet_id'], ['projet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'organisation', ['organisation_id'], ['id'])

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'compte_comptable', ['compte_comptable_id'], ['id'])
        batch_op.create_foreign_key(None, 'organisation', ['organisation_id'], ['id'])

    with op.batch_alter_table('compte_comptable', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'organisation', ['organisation_id'], ['id'])

    with op.batch_alter_table('ecriture_comptable', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'exercice_comptable', ['exercice_id'], ['id'])
        batch_op.create_foreign_key(None, 'organisation', ['organisation_id'], ['id'])

    with op.batch_alter_table('equipe_membre', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'app_user', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'projet', ['projet_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('exercice_comptable', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'organisation', ['organisation_id'], ['id'])

    with op.batch_alter_table('financial_transaction', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'compte_comptable', ['compte_id'], ['id'])
        batch_op.create_foreign_key(None, 'organisation', ['organisation_id'], ['id'])
        batch_op.create_foreign_key(None, 'exercice_comptable', ['exercice_id'], ['id'])
        batch_op.create_foreign_key(None, 'projet', ['projet_id'], ['id'])
        batch_op.create_foreign_key(None, 'app_user', ['user_id'], ['id'])

    with op.batch_alter_table('jalon', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'projet', ['projet_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'project_phase', ['phase_id'], ['id'])

    with op.batch_alter_table('ligne_ecriture', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'ecriture_comptable', ['ecriture_id'], ['id'])
        batch_op.create_foreign_key(None, 'compte_comptable', ['compte_id'], ['id'])

    with op.batch_alter_table('notes_reunion', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'projet', ['projet_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('project_phase', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'projet', ['projet_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'organisation', ['organisation_id'], ['id'])
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])
        batch_op.create_foreign_key(None, 'app_user', ['user_id'], ['id'])

    with op.batch_alter_table('whiteboard', schema=None) as batch_op:
        batch_op.drop_index('fk_whiteboard_projet')
        batch_op.create_foreign_key('fk_whiteboard_projet', 'projet', ['projet_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whiteboard', schema=None) as batch_op:
        batch_op.drop_constraint('fk_whiteboard_projet', type_='foreignkey')
        batch_op.create_index('fk_whiteboard_projet', ['projet_id'], unique=False)

    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('project_phase', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('notes_reunion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ligne_ecriture', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('jalon', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('financial_transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('exercice_comptable', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('equipe_membre', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ecriture_comptable', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('compte_comptable', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('rag_document')
    # ### end Alembic commands ###
