"""empty message

Revision ID: 88b6252a3d91
Revises: a0962444cde3
Create Date: 2025-03-28 19:09:34.745864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b6252a3d91'
down_revision = 'a0962444cde3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
