"""Add siret, tva_intracommunautaire, and forme_juridique to Organisation model

Revision ID: a00905b9bf53
Revises: c7acd10576ea
Create Date: 2025-03-28 18:17:52.690509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00905b9bf53'
down_revision = 'c7acd10576ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
