"""empty message

Revision ID: acfaed84d1b8
Revises: 0679232fcf8f
Create Date: 2025-03-26 19:48:50.025995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acfaed84d1b8'
down_revision = '0679232fcf8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_creation', sa.DateTime(), nullable=True))
        batch_op.alter_column('user_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        batch_op.drop_column('date_creation')
    # ### end Alembic commands ###
