"""empty message

Revision ID: b0c577991ae0
Revises: 88b6252a3d91
Create Date: 2025-03-28 19:12:02.640778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c577991ae0'
down_revision = '88b6252a3d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
