"""Change Float to Numeric for monetary values

Revision ID: b52c6cee3a51
Revises: a4b63b559c0c
Create Date: 2025-04-17 12:22:12.310209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b52c6cee3a51'
down_revision = 'a4b63b559c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'compte_comptable', ['compte_comptable_id'], ['id'])
        batch_op.create_foreign_key(None, 'organisation', ['organisation_id'], ['id'])

    with op.batch_alter_table('compte_comptable', schema=None) as batch_op:
        batch_op.alter_column('solde_initial',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'organisation', ['organisation_id'], ['id'])

    with op.batch_alter_table('ecriture_comptable', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'exercice_comptable', ['exercice_id'], ['id'])
        batch_op.create_foreign_key(None, 'organisation', ['organisation_id'], ['id'])

    with op.batch_alter_table('equipe_membre', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'projet', ['projet_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('exercice_comptable', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'organisation', ['organisation_id'], ['id'])

    with op.batch_alter_table('jalon', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'projet', ['projet_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'phase', ['phase_id'], ['id'])

    with op.batch_alter_table('ligne_ecriture', schema=None) as batch_op:
        batch_op.alter_column('montant_debit',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('montant_credit',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'compte_comptable', ['compte_id'], ['id'])
        batch_op.create_foreign_key(None, 'ecriture_comptable', ['ecriture_id'], ['id'])

    with op.batch_alter_table('phase', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'projet', ['projet_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.alter_column('prix_total',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'organisation', ['organisation_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('montant',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'projet', ['projet_id'], ['id'])
        batch_op.create_foreign_key(None, 'exercice_comptable', ['exercice_id'], ['id'])
        batch_op.create_foreign_key(None, 'organisation', ['organisation_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'compte_comptable', ['compte_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'organisation', ['organisation_id'], ['id'])

    with op.batch_alter_table('whiteboard', schema=None) as batch_op:
        batch_op.drop_index('fk_whiteboard_projet')
        batch_op.create_foreign_key('fk_whiteboard_projet', 'projet', ['projet_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whiteboard', schema=None) as batch_op:
        batch_op.drop_constraint('fk_whiteboard_projet', type_='foreignkey')
        batch_op.create_index('fk_whiteboard_projet', ['projet_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('montant',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('prix_total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('phase', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ligne_ecriture', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('montant_credit',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('montant_debit',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('jalon', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('exercice_comptable', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('equipe_membre', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ecriture_comptable', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('compte_comptable', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('solde_initial',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
