"""Ajout des champs logo et logo_mimetype à Organisation

Revision ID: c0057970ec1b
Revises: dcbfb0fc9abb
Create Date: 2025-03-26 17:57:26.016043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0057970ec1b'
down_revision = 'dcbfb0fc9abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_mimetype', sa.String(length=50), nullable=True))
        batch_op.alter_column('logo',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.alter_column('logo',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('logo_mimetype')

    # ### end Alembic commands ###
