"""Add IBAN, BIC, and VAT exemption to Organisation model

Revision ID: c7acd10576ea
Revises: fae3c3bf843f
Create Date: 2025-03-28 11:01:57.025910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7acd10576ea'
down_revision = 'fae3c3bf843f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('iban', sa.String(length=34), nullable=True))
    op.add_column('organisation', sa.Column('bic', sa.String(length=11), nullable=True))
    op.add_column('organisation', sa.Column('exonere_tva', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'exonere_tva')
    op.drop_column('organisation', 'bic')
    op.drop_column('organisation', 'iban')
    # ### end Alembic commands ###
