"""empty message

Revision ID: cbf6b12c62af
Revises: b0c577991ae0
Create Date: 2025-03-28 19:12:55.239421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf6b12c62af'
down_revision = 'b0c577991ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercice_comptable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transaction', sa.Column('exercice_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'exercice_comptable', ['exercice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'exercice_id')
    op.drop_table('exercice_comptable')
    # ### end Alembic commands ###
