"""Add CompteComptable model and link to transaction

Revision ID: d1310cb15294
Revises: d76a33e3781e
Create Date: 2025-04-09 09:11:05.632749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1310cb15294'
down_revision = 'd76a33e3781e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compte_comptable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero', 'organisation_id', name='uq_compte_numero_organisation')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compte_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_transaction_compte_comptable_compte_id', 'compte_comptable', ['compte_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_compte_comptable_compte_id', type_='foreignkey')
        batch_op.drop_column('compte_id')

    op.drop_table('compte_comptable')
    # ### end Alembic commands ###
