"""Add progress column to Phase model

Revision ID: d76a33e3781e
Revises: 3c06441a8fd4
Create Date: 2025-04-05 23:49:01.060123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd76a33e3781e'
down_revision = '3c06441a8fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phase', schema=None) as batch_op:
        batch_op.drop_column('progress')

    # ### end Alembic commands ###
