"""empty message

Revision ID: dcbfb0fc9abb
Revises: 8bbf96bdd84e
Create Date: 2025-03-26 16:41:12.019359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcbfb0fc9abb'
down_revision = '8bbf96bdd84e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_postal', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('ville', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.drop_column('ville')
        batch_op.drop_column('code_postal')

    # ### end Alembic commands ###
