"""Add reglement field to Transaction model

Revision ID: e85efbd9b3e1
Revises: 060816fda31f
Create Date: 2025-03-29 14:03:03.643111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e85efbd9b3e1'
down_revision = '060816fda31f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reglement', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('reglement')

    # ### end Alembic commands ###
