"""Make prix_total not nullable in Projet model

Revision ID: f1639aab3d7b
Revises: 00e2a7c0ae1e
Create Date: 2025-03-26 10:42:49.372969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1639aab3d7b'
down_revision = '00e2a7c0ae1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projet', schema=None) as batch_op:
        # Update existing rows with NULL prix_total to 0
        batch_op.execute("UPDATE projet SET prix_total = 0 WHERE prix_total IS NULL")
        batch_op.alter_column('prix_total',
                existing_type=sa.INTEGER(),
                nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.alter_column('prix_total',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_projet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nom', sa.VARCHAR(length=100), nullable=False),
    sa.Column('client', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date_debut', sa.DATE(), nullable=True),
    sa.Column('date_fin', sa.DATE(), nullable=True),
    sa.Column('statut', sa.VARCHAR(length=20), nullable=True),
    sa.Column('prix_total', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
