"""Describe your changes here

Revision ID: fae3c3bf843f
Revises: 427d569f92a2
Create Date: 2025-03-28 10:08:35.384864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae3c3bf843f'
down_revision = '427d569f92a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
